# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://172.24.144.1:5433/appdbvue?sslmode=disable
spring.datasource.username=adminbckvue
spring.datasource.password=StrongPassw0rd-2028!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# JWT Properties
# IMPORTANT: Use a strong, long, and random secret in production.
# You can generate one from a site like https://www.lastpass.com/features/password-generator
jwt.secret=]"*40vas&\r#4}Dp:hlvF_hBUh0abz*L&^Z|'4hgKKsAA~4c/D
jwt.expiration-ms=86400000
# Expiration time in milliseconds (e.g., 86400000ms = 24 hours)
# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true
